# Generated by Django 3.2.11 on 2022-02-17 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='deleted_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
