# Generated by Django 3.2.11 on 2022-02-17 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_profile_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='resume',
            field=models.FileField(default=None, upload_to='media/%Y %m %d'),
        ),
    ]
