# Generated by Django 3.2.11 on 2022-02-17 19:03

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_profile_resume'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='resume',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to=api.models.path_and_rename),
        ),
    ]
