# Generated by Django 3.2.11 on 2022-02-17 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_profile_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='deleted_on',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
    ]
