# Generated by Django 3.2.11 on 2022-02-18 20:41

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_profile_resume_list'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='resume_list',
            new_name='prev_resume_list',
        ),
        migrations.AlterField(
            model_name='profile',
            name='count',
            field=models.IntegerField(default=1, editable=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='resume',
            field=models.FileField(blank=True, default=None, max_length=255, null=True, upload_to=api.models.path_and_rename),
        ),
    ]
